### ISSUE TITLE
Cannot compile on mac with vtk 8.1.1

### ISSUE THREAD

**Issue by MinZe25** [zippy84/vtkbool#13]
Hi, I tried to compile vtkbool but I've got some issues.
I could generate the xcode project but I had to delete pythronWrapper from CMakelists.txt (I'm gonna use c++ so I don't really care) and I had to comment the replace line on the if (vtk_found)
After those two changes I'm able to build xcode, but I'm not able to build the project because of vp that includes <algorithm> and xcode says that it has invalid operations and not matching functions (?)
![image](https://user-images.githubusercontent.com/22060140/43146940-42613596-8f62-11e8-9c34-e2160a199d1a.png)
Is there any way to fix those errors? or that someone could share their compiled libraries with me?

**Comment by zippy84** [comment]
Could you please point to the line where the error occurs? It is difficult to say what is wrong, because I don't have a mac. But I try my best to find a fix for it.

**Comment by MinZe25** [comment]
Thanks for answering so fast!
I disabled vp from the build and that errors are fixed... somehow
Is vp important for the booleanUnion operation?
Right now I have another error:
> ld: library not found for -lvtkFiltersSources
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

But is seems Mac-related, so don't worry if you can't or don't want to solve it

**Comment by MinZe25** [comment]
So, lvtkIOLegacy and vtkFiltersSources (for now) are giving me problems because vtk doesn't have those, it's possible that because I'm using VTK 8.1.1 those doesn't exist right now?

**Comment by zippy84** [comment]
vp is essential for the decomposition of non-convex polygons. For my development I'm using VTK 6.3. But vtkFiltersSources should also exists in VTK 8. I have no idea why it is missing. Try to ask it on VTK's mailing list.

**Comment by zippy84** [comment]
I just tested it with clang 6.0.1 and it can be compiled without errors. On my other machine I'm using VTK 7 and the shared object libvtkFiltersSources-7.1.so also exists.

**Comment by MinZe25** [comment]
Thanks for all the answers!
I've confirmed that the libraries exists, though xcode can't find them.
Would you mind writting the steps that you follow to build vtkbool as a library? Maybe I am doing it wrong
What I do with cmake is:
![image](https://user-images.githubusercontent.com/22060140/43183904-09c5be16-8fe7-11e8-87c2-1cae4754c9fb.png)

And it generates me an xcode project, from where I try to build that library.
I've been doing this for vtk projects that I have without problems.

**Comment by MinZe25** [comment]
If I try to build it with
```
$ cmake ..
$ make
```
it gives me an error on the 38% and I still need to delete pythonwrapper and the string replace.
![image](https://user-images.githubusercontent.com/22060140/43185019-f276b50e-8fea-11e8-9a0d-a0111df381ef.png)
I'm downloading vtk6 to test

**Comment by MinZe25** [comment]
Tried on linux... worked first try (without string replace and without pythonwrapper)

**Comment by zippy84** [comment]
Maybe your VTK_DIR is wrong. For me it is `/home/zippy/VTK6/lib/cmake/vtk-6.3`.

**Comment by MinZe25** [comment]
I've solved everything :D
