### ISSUE TITLE
boolean Union is giving an output of 0 meshes even with just 2 cubes

### ISSUE THREAD

**Issue by MinZe25** [zippy84/vtkbool#14]
Im trying to do a boolean union but the output gives me a polydata with 0 polygons, even with just two cubes
![screenshot from 2018-07-25 13-00-17](https://user-images.githubusercontent.com/22060140/43197205-b97b03ca-900a-11e8-9dff-53656dda9d46.png)
This is what I'm doing:
(components is a vector with vtkPolyDatas)
![screenshot from 2018-07-25 13-01-16](https://user-images.githubusercontent.com/22060140/43197304-0ff0c78a-900b-11e8-95e3-a3f0d3b8b464.png)

**Comment by MinZe25** [comment]
Unfortunately they are not :disappointed:
![image](https://user-images.githubusercontent.com/22060140/43201679-729d6312-9019-11e8-8c5e-4d8d698006ce.png)
Do you have discord / slack / skype to speak? Maybe I've done something wrong related to the build or something

**Comment by zippy84** [comment]
Could you please paste your code at https://pastebin.com/.

**Comment by MinZe25** [comment]
https://pastebin.com/EH7Vs14B

**Comment by MinZe25** [comment]
It's true that the number of cells is higher, but I exported the output directly, and It still gives me an stl with 0 vertex

**Comment by zippy84** [comment]
Please share your project or a minified version of it on Github or Gitlab. Without it I can not say what is wrong with your code.

**Comment by MinZe25** [comment]
Well, this is everything related to booleans...and I'm not allowed to share more code

**Comment by zippy84** [comment]
Unfortunalty you have to find out for yourself. I can't say what's wrong, but the lib works correct for such a simple case.

**Comment by MinZe25** [comment]
Well, thanks anyway ^^

**Comment by MinZe25** [comment]
In the readme you say that the result is stored in GetOutputPort(0), But I'm using GetOutput() (which give me vtkPolyData) is there anything wrong with this?

**Comment by zippy84** [comment]
The result should also be accessible via `GetOuput()`. Check the output of `bf->GetOutput()->Print(std::cout)`.

**Comment by zippy84** [comment]
Ok, the result is empty. The only one reason for that is, the PolyData's do not intersect. Please enable BUILD_AS_DEBUG within cmake and examine modPdA.vtk and modPdB.vtk in ParaView or another program.

**Comment by MinZe25** [comment]
So, I changed
```
bf->SetInputData(components[0]);
```
to
```
bf->SetInputData(0, components[0]);
```
And it's working!!
but right now after some booleans it's given this error (not always and not with all the models)
```
stlJoiner: ~/dev/vtkbool/libs/decomp/Decomposer.cxx:208: void Decomposer::Forw(int, int, int): Assertion `!subs[p].S.empty()' failed.
Aborted (core dumped)
```

**Comment by zippy84** [comment]
That's a problem with the Decomposer I'm actually working on. Please comment https://github.com/zippy84/vtkbool/blob/0ea25f545d89517dcc6f4baf11f8ebdec71fcaa3/vtkPolyDataBooleanFilter.cxx#L412-L413 this out and it should work fine.

**Comment by MinZe25** [comment]
Okay, I just did it but now there is another assertion fail :(
```
stlJoiner: /home/aitorgarcia/dev/vtkbool/vtkPolyDataBooleanFilter.cxx:2317: PolyPair GetEdgePolys(vtkPolyData*, vtkIdList*, vtkIdList*): Assertion `opp.size() == 2' failed.
```
Sorry for all the troubles though.

**Comment by zippy84** [comment]
Please provide modPdA.vtk and modPdB.vtk that cause the problem.

**Comment by MinZe25** [comment]
Are those 3D files?
I'm using stl. Do you want me to send it to you?

**Comment by zippy84** [comment]
If you build vtkbool with `BUILD_AS_DEBUG` (in the advanced settings) and run your program, the files will be created in your working directory.

**Comment by MinZe25** [comment]
Okey, doing it right now!

**Comment by MinZe25** [comment]
I suppose that it's just those two

[modPd.zip](https://github.com/zippy84/vtkbool/files/2228429/modPd.zip)

**Comment by zippy84** [comment]
The boolean operation can not be performed because of this situation:

![fail](https://user-images.githubusercontent.com/373343/43210244-dafaac66-902e-11e8-8c6f-870437cafe6f.png)

My filter does not check it right now. I will change it in the next release.

**Comment by MinZe25** [comment]
Okey so if the mesh has some separated parts, It's not possible to perform the union?

**Comment by MinZe25** [comment]
Okay, so what would yo do? because I want to know if there is no union without crashing the program

**Comment by zippy84** [comment]
Replace the assertion with vtkErrorMacro and catch the error via https://www.vtk.org/Wiki/VTK/Examples/Cxx/Utilities/ObserveError.

**Comment by MinZe25** [comment]
Thanks! I'll give it a try

**Comment by zippy84** [comment]
Were you successful? Can I close this issue/question?

**Comment by zippy84** [comment]
Try the new version!
