### ISSUE TITLE
MSVC - unresolved external symbol "private: static int Point::_tag"

### ISSUE THREAD

**Issue by zippy84** [zippy84/vtkbool#15]
Put `int Point::_tag;` into Tools.cxx.

**Comment by zippy84** [comment]
If you want to compile vtkbool as a plugin for ParaView you have to remove `int Point::_tag;` at the end of Tools.cxx.

**Comment by bluelightning32** [comment]
Maybe you could use weak symbols to fix this?
https://stackoverflow.com/questions/2290587/gcc-style-weak-linking-in-visual-studio

However, it looks like you're using _tag in a non-thread safe way. Are the tags just for debugging purposes?

**Comment by zippy84** [comment]
Yes you are right, it's currently not threadsafe. No, _tag is very important. It's not just for debugging. It's the initialization of a static variable.

**Comment by zippy84** [comment]
Not present anymore
