### ISSUE TITLE
Get an error when build the project

### ISSUE THREAD

**Issue by wzx140** [zippy84/vtkbool#17]
Hello developer, I get a problem when I use the vtkbool. I copy the dir in my project and add `add_subdirectory(vtkbool-2.5.2)` in the root *CMakeLists.txt*. When I build my project, I get an error.
```
In file included from /home/wzx/CLionProjects/tube_connect/test/util/../../util/../vtkbool-2.5.2/vtkPolyDataBooleanFilter.h:30,
                 from /home/wzx/CLionProjects/tube_connect/test/util/../../util/TubeUtil.h:21,
                 from /home/wzx/CLionProjects/tube_connect/test/util/TubeUtilTest.cpp:7:
/home/wzx/CLionProjects/tube_connect/test/util/../../util/../vtkbool-2.5.2/Utilities.h:27:10: Fatal error：Tools.h：No such file or directory
 #include "Tools.h"
          ^~~~~~~~~
```

**Comment by zippy84** [comment]
Thanks for the issue. I need a verbose output:

```
cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .
make
```

**Comment by zippy84** [comment]
A minimal example is this:

```c++
#include <vtkCubeSource.h>
#include <vtkCylinderSource.h>

#include "vtkPolyDataBooleanFilter.h"

int Point::_tag = 0; // important!

int main (int argc, char *argv[]) {
    vtkCubeSource *cu = vtkCubeSource::New();
    cu->SetYLength(.5);

    vtkCylinderSource *cyl = vtkCylinderSource::New();
    cyl->SetResolution(32);
    cyl->SetHeight(.5);
    cyl->SetCenter(0, .5, 0);

    vtkPolyDataBooleanFilter *bf = vtkPolyDataBooleanFilter::New();
    bf->SetInputConnection(0, cu->GetOutputPort());
    bf->SetInputConnection(1, cyl->GetOutputPort());
    bf->SetOperModeToDifference();
    bf->Update();

    bf->Delete();
    cyl->Delete();
    cu->Delete();

    return 0;
}
```

```CMake
cmake_minimum_required(VERSION 3.1)
project(bla)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include_directories(vtkbool-1)

add_subdirectory(vtkbool-1)

find_package(VTK REQUIRED COMPONENTS vtkFiltersSources NO_MODULE)
include(${VTK_USE_FILE})

include_directories(vtkbool-1/libs/vp)

add_executable(bla testing.cxx)
target_link_libraries(bla ${VTK_LIBRARIES} vtkbool)
```

Hope that helps.

**Comment by wzx140** [comment]
Thank you for your help. Your example run well. 

By read your code, I find the root of the error. I use `find_package(VTK REQUIRED)` instead of `find_package(VTK REQUIRED COMPONENTS xxx)`. Before use your library, my project run well. I confuse about that why this is happening.

Another question. How can I use your library besides `add_subdirectory(vtkbool)`. I use cmake to generate makefile and `make`. In build path, there is no thing to install(`make install`) and no `header files` and `lib files`, just a `libvtkbool.so`. 

A little suggestion. My VTK is not Python wrapped. So I delete code about python in *CMakeLists.txt*. I think a option about python_wrapper is needed.

**Comment by zippy84** [comment]
Actually there is no install routine. There is no plan for this.

**Comment by wzx140** [comment]
Thank you for your patience. My problem is solved.
