### ISSUE TITLE
SetOperModeToDifference result missing components

### ISSUE THREAD

**Issue by yangminglong** [zippy84/vtkbool#19]
### Issue
The result missing components when the input model has mult components. 
### Preview
[Input A B preview](https://github.com/yangminglong/Data/blob/master/bunny_and_punching.png)
[Output preview](https://github.com/yangminglong/Data/blob/master/bunny_diff_puching_result.png)
### Input Model
[input A](https://github.com/yangminglong/Data/blob/master/bunny.stl) 
[input B](https://github.com/yangminglong/Data/blob/master/punching.stl)
### Test code
```
#include "stdafx.h"
#include "vtkRenderer.h"
#include "vtkRenderWindow.h"
#include "vtkRenderWindowInteractor.h"
#include "vtkPolyDataMapper.h"
#include "vtkActor.h"
#include "vtkProperty.h"
#include "vtkCamera.h"
#include "vtkSTLReader.h"
#include "vtkPolyDataBooleanFilter.h" 
#include "vtkNew.h"

int main()
{
  vtkNew<vtkSTLReader> pReaderA;
  pReaderA->SetFileName("../bunny.stl"); 
  pReaderA->Update();

  vtkNew<vtkSTLReader> pReaderB ;
  pReaderB->SetFileName("../punching.stl"); 
  pReaderB->Update();

  vtkNew<vtkPolyDataBooleanFilter> bf;
  bf->SetInputData(0, pReaderA->GetOutput());
  bf->SetInputData(1, pReaderB->GetOutput());
  bf->SetOperModeToDifference();
  bf->Update();

  vtkNew<vtkPolyDataMapper> polyDataMapper;
  polyDataMapper->SetInputData(bf->GetOutput());

  vtkNew<vtkActor> polyDataActor;
  polyDataActor->SetMapper(polyDataMapper);
  polyDataActor->GetProperty()->SetColor(1.0000, 0.3882, 0.2784);

  vtkNew<vtkRenderer> ren1;
  vtkNew<vtkRenderWindow> renWin;
  renWin->AddRenderer(ren1);
  vtkNew<vtkRenderWindowInteractor> iren;
  iren->SetRenderWindow(renWin);

  ren1->AddActor(polyDataActor);

  ren1->SetBackground(0.1, 0.2, 0.4);
  renWin->SetSize(200, 200);

  ren1->ResetCamera();
  ren1->GetActiveCamera()->Zoom(1.5);
  renWin->Render();

  // This starts the event loop and as a side effect causes an initial render.
  iren->Start();

  return 0;
}
```

**Comment by zippy84** [comment]
There are missing regions, because they are not involved in the contact.

**Comment by zippy84** [comment]
Try to modify CombineRegions() to your own. You only have to identify regions that are not involved in the contact. Pass them to cfA and cfB. It's not as difficult as it sounds.

**Comment by yangminglong** [comment]
Thanks for your reply,  There are missing regions too if i SetOperModeToUnion [preview union result](https://github.com/yangminglong/Data/blob/master/bunny_union_puching_result.png)
I am VTK learners, modify the vtkbool is difficult to me, could you enhancement it?

**Comment by bluelightning32** [comment]
My bug got marked as a duplicate to this one. zippy84, in your last comment are you suggesting that I create a pull request that modifies CombineRegions to fix it?

Your code comments are in German, which I don't understand. I'll try using Google Translate on them.

Is there a book or paper that you based your algorithm on?

**Comment by zippy84** [comment]
@bluelightning32 Unfortunately there is no written word about it.

**Comment by zippy84** [comment]
This is now implemented :smiley:

**Comment by bluelightning32** [comment]
Thank you so much for making progress on this! I was slowly reading a book about computer graphics in hopes that I can ramp up to do it myself.

I synced to d2166f02, but the union of disjoint objects still isn't working for me. I still get this error:
```
ERROR: In /home/kyle/nrf/vtk_print_examples/vtkbool/vtkPolyDataBooleanFilter.cxx, line 186
vtkPolyDataBooleanFilter (0x18fa280): Inputs have no contact.
```
