### ISSUE TITLE
Issues compiling the library

### ISSUE THREAD

**Issue by zandarina** [zippy84/vtkbool#20]
Hi,

Thank you for your library. I tried to compile the library but i got many errors. First in cmake as i am not using python i had to delete all the  vtkWrappingPythonCore references , otherwise i got an error.  I also deleted this line string(REPLACE "/" "\\" vtk_lib ${VTK_INSTALL_PREFIX}) as it was causing me an error saying that it requires 4 parameters. Doing this, I was able to generate the project linking with my vtk binary bolder. I am using windows withn vs2105.

The problem came when i built the project. I got many errors of missing libraries ans also some functions as back_inserts is not member of std and also some more error of linkage.

Coud you tell me what i am doing wrong with the installation?. i think it might be for something i deleted but i do not want to install python and the replace line does not work and i do not understand why.

Thank you

The cmake modified

cmake_minimum_required(VERSION 3.1)
project(vtkbool VERSION 2.6)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if(MSVC)
    set(CMAKE_CXX_FLAGS "/EHsc")
    add_definitions(-D_SCL_SECURE_NO_WARNINGS)
    set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
else()
    set(CMAKE_CXX_FLAGS "-Wno-deprecated -fPIC -Wunused")
endif()

option(BUILD_PARAVIEW_PLUGIN "" OFF)
option(BUILD_AS_DEBUG "" OFF)
option(BUILD_TESTING "" OFF)

mark_as_advanced(BUILD_AS_DEBUG)

set(srcs
    vtkPolyDataBooleanFilter.cxx
    vtkPolyDataContactFilter.cxx
    Utilities.cxx)

include_directories(".")

if(BUILD_AS_DEBUG)
    add_definitions(-DDEBUG)
endif()

if(BUILD_PARAVIEW_PLUGIN)
    set(BUILD_TESTING OFF CACHE BOOL "" FORCE)

    add_subdirectory(paraview_plugin ${CMAKE_BINARY_DIR}/paraview_plugin)

else()

    #unset(VTK_DIR CACHE)

    find_package(VTK REQUIRED COMPONENTS vtkFiltersSources vtkIOLegacy vtkFiltersExtraction vtkFiltersGeometry vtkFiltersModeling vtkRenderingFreeType  NO_MODULE)

    if(VTK_FOUND)
        include(${VTK_USE_FILE})

        add_subdirectory(libs)

        include_directories(libs/merger libs/decomp libs/vp libs/aabb)

        add_library(${PROJECT_NAME} SHARED ${srcs})
        target_link_libraries(${PROJECT_NAME} ${VTK_LIBRARIES} decomp merger)

       

        if(BUILD_TESTING)
            enable_testing()

            add_executable(testing testing/testing.cxx)
            target_link_libraries(testing ${PROJECT_NAME} ${VTK_LIBRARIES})

            foreach(i RANGE 19)
                add_test(NAME Test_${i} COMMAND testing ${i})

                if(WIN32)
                    set_property(TEST Test_${i} PROPERTY ENVIRONMENT "PATH=${vtk_lib}\\bin")
                endif()

            endforeach()

        endif()

        if(VTK_WRAP_PYTHON)

            set(ENV{LD_LIBRARY_PATH} "${VTK_INSTALL_PREFIX}/lib")

            execute_process(COMMAND "${VTK_INSTALL_PREFIX}/bin/vtkpython" -c "import sys; sys.stdout.write('.'.join(map(str, sys.version_info[:2])))" OUTPUT_VARIABLE py_version)

            if(CMAKE_VERSION VERSION_LESS "3.12")
                find_package(PythonInterp "${py_version}")
                find_package(PythonLibs "${py_version}")

                if(PYTHONLIBS_FOUND)

                    include_directories(${PYTHON_INCLUDE_DIRS} ${PROJECT_SOURCE_DIR})

                    include(vtkWrapPython)

                    vtk_wrap_python3(${PROJECT_NAME}Python ${PROJECT_NAME}Python_srcs vtkPolyDataBooleanFilter.cxx)

                    add_library(${PROJECT_NAME}PythonD ${${PROJECT_NAME}Python_srcs})
                    target_link_libraries(${PROJECT_NAME}PythonD ${PROJECT_NAME}  vtkCommonExecutionModelPythonD)

                    python_add_module(${PROJECT_NAME}Python PyInit.cxx ${PROJECT_NAME}PythonInit.cxx)
                    target_link_libraries(${PROJECT_NAME}Python PRIVATE ${PROJECT_NAME}PythonD)

                    if(BUILD_TESTING)
                        add_test(NAME Test_Py COMMAND ${PYTHON_EXECUTABLE}
                            ${CMAKE_SOURCE_DIR}/testing/test_py_module.py
                            ${VTK_INSTALL_PREFIX}/lib/python${py_version}/site-packages
                            ${CMAKE_BINARY_DIR}
                            $<CONFIG>)

                        if(WIN32)
                            set_property(TEST Test_Py PROPERTY ENVIRONMENT "PATH=${vtk_lib}\\bin")
                        else()
                            set_property(TEST Test_Py PROPERTY ENVIRONMENT "LD_LIBRARY_PATH=${VTK_INSTALL_PREFIX}/lib")
                        endif()
                    endif()

                endif()

            else()
                if (py_version MATCHES "^3")
                    find_package(Python3 COMPONENTS Interpreter Development)

                    if(Python3_Development_FOUND)

                        include_directories(${PYTHON_INCLUDE_DIRS} ${PROJECT_SOURCE_DIR})

                        include(vtkWrapPython)

                        vtk_wrap_python3(${PROJECT_NAME}Python ${PROJECT_NAME}Python_srcs vtkPolyDataBooleanFilter.cxx)

                        add_library(${PROJECT_NAME}PythonD ${${PROJECT_NAME}Python_srcs})
                        target_link_libraries(${PROJECT_NAME}PythonD ${PROJECT_NAME}  vtkCommonExecutionModelPythonD)

                        Python3_add_library(${PROJECT_NAME}Python MODULE PyInit.cxx ${PROJECT_NAME}PythonInit.cxx)
                        target_link_libraries(${PROJECT_NAME}Python PRIVATE ${PROJECT_NAME}PythonD)

                        if(BUILD_TESTING)
                            add_test(NAME Test_Py COMMAND ${Python3_EXECUTABLE}
                                ${CMAKE_SOURCE_DIR}/testing/test_py_module.py
                                ${VTK_PYTHONPATH}
                                ${CMAKE_BINARY_DIR}
                                $<CONFIG>)

                            if(WIN32)
                                set_property(TEST Test_Py PROPERTY ENVIRONMENT "PATH=${vtk_lib}\\bin")
                            else()
                                set_property(TEST Test_Py PROPERTY ENVIRONMENT "LD_LIBRARY_PATH=${VTK_INSTALL_PREFIX}/lib")
                            endif()
                        endif()
                    endif()

                elseif(py_version EQUAL "2.7")
                    find_package(Python2 COMPONENTS Interpreter Development)

                    if(Python2_Development_FOUND)

                        include_directories(${PYTHON_INCLUDE_DIRS} ${PROJECT_SOURCE_DIR})

                        include(vtkWrapPython)

                        vtk_wrap_python3(${PROJECT_NAME}Python ${PROJECT_NAME}Python_srcs vtkPolyDataBooleanFilter.cxx)

                        add_library(${PROJECT_NAME}PythonD ${${PROJECT_NAME}Python_srcs})
                        target_link_libraries(${PROJECT_NAME}PythonD ${PROJECT_NAME}  vtkCommonExecutionModelPythonD)

                        Python2_add_library(${PROJECT_NAME}Python MODULE PyInit.cxx ${PROJECT_NAME}PythonInit.cxx)
                        target_link_libraries(${PROJECT_NAME}Python PRIVATE ${PROJECT_NAME}PythonD)

                        if(BUILD_TESTING)
                            add_test(NAME Test_Py COMMAND ${Python2_EXECUTABLE}
                                ${CMAKE_SOURCE_DIR}/testing/test_py_module.py
                                ${VTK_PYTHONPATH}
                                ${CMAKE_BINARY_DIR}
                                $<CONFIG>)

                            if(WIN32)
                                set_property(TEST Test_Py PROPERTY ENVIRONMENT "PATH=${vtk_lib}\\bin")
                            else()
                                set_property(TEST Test_Py PROPERTY ENVIRONMENT "LD_LIBRARY_PATH=${VTK_INSTALL_PREFIX}/lib")
                            endif()
                        endif()
                    endif()

                endif()

            endif()

        endif()

    endif(VTK_FOUND)

endif()

**Comment by zippy84** [comment]
Could you please show me the error-messages. Use http://pastebin.com

**Comment by zandarina** [comment]
Thank you for answering.

The errors in cmake are:

https://pastebin.com/yudRC7wh
Then, I remove this pithon library in the cmake file as i do not use python
and i get the following error
https://pastebin.com/2kgjcerD

CMake Error at CMakeLists.txt:67 (string):
string sub-command REPLACE requires at least four arguments.

I remove that line: string(REPLACE "/" "\\" vtk_lib ${VTK_INSTALL_PREFIX})
and i generate the project with no errors

Then i open it, in visual c++ 2015 and i build it. And i get all these
errors:

https://pastebin.com/UR6n9BJN

Error C2039 'back_inserter': is not a member of 'std' vp
C:\Users\project\Desktop\vtkbool-master\vtkbool-master\libs\vp\VisPoly.cxx
602
Severity Code Description Project File Line Suppression State
Error MSB3073 The command "setlocal

I wonder if the problem is because of the modifications of the cmake.

Thanks
Cheers

**Comment by zippy84** [comment]
Is ${VTK_INSTALL_PREFIX} empty? Could you please verify it with a simple `message(WARNING ${VTK_INSTALL_PREFIX})` right before the replace statement.

**Comment by zippy84** [comment]
Here is a partial fix for your compiler f154b4d.

**Comment by zippy84** [comment]
Should work now. You also have to remove the `//` from this line https://github.com/zippy84/vtkbool/blob/f817f689b66fdfd76dc9f05f91552d657015bd8b/libs/vp/Tools.cxx#L283

**Comment by zandarina** [comment]
Hi, thank you for answering. I uncommented this line you mentioned but i
still have those errors

https://pastebin.com/N6NifT9r

decomp.lib is missing and it does not recognize back_inserter

Thanks

**Comment by zippy84** [comment]
You are still using the master! Clone/Download this branch https://github.com/zippy84/vtkbool/tree/vs2015.

**Comment by zandarina** [comment]
Thank you !! It works !! Thank you very much

**Comment by zandarina** [comment]
Hi, I have tried to dowload this branch again but it is not available
anymore. Could you upload it again?.

Thanks

**Comment by zippy84** [comment]
You don't need that branch. It is already part of master.

**Comment by zandarina** [comment]
Hi,

It is because i get another error with this new master version. So i wonder
if i can go back to the previous version. Thanks

Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.17763.

CMake Error at CMakeLists.txt:66 (find_package):
Could not find a configuration file for package "VTK" that is compatible
with requested version "".

The following configuration files were considered but not accepted:

C:/Users/Desktop/vtk_final/VTKConfig.cmake, version: 8.2.0 (64bit)


Configuring incomplete, errors occurred!

See also "C:/Users/Desktop/vtkbook_bin/CMakeFiles/CMakeOutput.log".


Thanks

**Comment by zippy84** [comment]
I thinks it's a problem of VTK. It works fine with VS 2017 and VTK 8.2: https://ci.appveyor.com/project/zippy84/vtkbool/build/job/htmmp6nl2d72lv11

**Comment by zandarina** [comment]
yes, it was that. Thank you !!
