### ISSUE TITLE
boolean error

### ISSUE THREAD

**Issue by jack845** [zippy84/vtkbool#21]
Hi zippy84, 
                 first of all thank you very much for this great project. 
I'm testing some boolean operation: the filter perform ok, but sometimes it fails. I attach a testcase with a minimal code and 2 test polydata.
The error is: vtkPolyDataBooleanFilter (000001CE689D23D0): Contact is ambiguous or incomplete (at line 33). 
Can you have some suggestion to avoid this kind of errors?
Thank you very much in advance.

[boolean_test.zip](https://github.com/zippy84/vtkbool/files/3334457/boolean_test.zip)

**Comment by zippy84** [comment]
PolyA.stl is an invalid mesh. There are at least two overlapping triangles, that causes the error. Here are some modified screenshots of the problem.

Here you can see two cutting lines at nearly the same place.

![overlapping_triangles](https://user-images.githubusercontent.com/373343/60294046-c97e1f80-9920-11e9-83b8-0ecafc67f7d2.png)

And this are the two overlapping triangles, filled with green:

![overlapping_triangles_1](https://user-images.githubusercontent.com/373343/60294047-c97e1f80-9920-11e9-9460-91c78e9ebad6.png)

![overlapping_triangles_2](https://user-images.githubusercontent.com/373343/60294048-c97e1f80-9920-11e9-8af5-692cc5c844c8.png)

My library actually does not have a mesh optimizer.

Hope that helps.

**Comment by jack845** [comment]
Thank you very much for the answer, so I must take care about input polydata. Do you know about some mesh optimizer, vtk based, we can try ?

**Comment by zippy84** [comment]
Unfortunately not. But you can try this https://github.com/zeux/meshoptimizer.

**Comment by zippy84** [comment]
Here is the recipe for how to handle such errors: https://github.com/zippy84/vtkbool/issues/18#issuecomment-469953653

**Comment by jack845** [comment]
Thank you again, for the answers and have nice week-end.
