### ISSUE TITLE
Head does not build on Fedora

### ISSUE THREAD

**Issue by bluelightning32** [zippy84/vtkbool#28]
I can build the 2.7.2 branch, but the head of vtkbool (26575b88c) does not build for me:
```
make[2]: *** No rule to make target 'vtkbool/vtkboolHierarchy.txt', needed by 'vtkbool/vtkPolyDataBooleanFilterPython.cxx'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:521: vtkbool/CMakeFiles/vtkboolPythonD.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

I'm using Fedora 30 with vtk-8.1.1-5.fc30.x86_64.

This is my [build](https://github.com/bluelightning32/vtk_print_examples/blob/master/CMakeLists.txt) file.

**Comment by zippy84** [comment]
Should be fixed now. Right?

**Comment by bluelightning32** [comment]
I tried syncing to f36349d. It has the same error:
```
make[2]: *** No rule to make target 'vtkbool/vtkboolHierarchy.txt', needed by 'vtkbool/vtkPolyDataBooleanFilterPython.cxx'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

Is there any other information you would like me collect? I'm not too familiar with cmake. Is vtkboolHierarchy.txt supposed to be created when I run `cmake` or when I run `make`?

**Comment by zippy84** [comment]
Finally it should work now :)

I also tried it with your Fedora version.

**Comment by bluelightning32** [comment]
Thanks! I can confirm it works now.
