### ISSUE TITLE
Python Wrappings with Ubuntu 18

### ISSUE THREAD

**Issue by sean-mcmahon** [zippy84/vtkbool#32]
Hi,
I've been trying unsuccessfully to get the vtkbool Python bindings to work with Python3, VTK7 on Ubuntu 18. I have to use Python3, but flexible on what VTK version to use.

As a sanity check, I've been following the steps from https://ci.appveyor.com/project/zippy84/vtkbool/builds/28398290/job/ikr5mvvms5eh1tip 
I've removed VTK from my system via "apt purge" and pip on my machine. 

I then run the commands:
```
sudo apt-get install -y libvtk7.1 libvtk7-dev python3-vtk7
ls /usr/bin/vtk*  # prints the same files as link above
mkdir build
cd build
cmake -DVTKBOOL_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
make
ctest
```
When I run the cmake, I get the same messages and warnings as the test and the same passes as `ctest`. However, there is no Test_Py created, same as the link above.

I think it's because there's no `${_vtk}/bin/vtkpython` command/file [here in CMakeLists.txt](https://github.com/zippy84/vtkbool/blob/master/CMakeLists.txt#L146) on my machine. When I manually set this to "3.6", the version working with my VTK Python wrappings, everything builds and compiles, but the test results in a seg fault. 

Here's the print out from the failing ctest: https://pastebin.com/hRvMd7jG
I've tried importing vtkBoolPython in an interactive python session but still getting a seg fault.

Any help on getting the python bindings to work would be greatly appreciated!

**Comment by zippy84** [comment]
Please build the lib with `make VERBOSE=1` and send me the output. Maybe there is a linker-problem. You can also check the .so with ldd. Or try to run it with gdb.

**Comment by sean-mcmahon** [comment]
Thanks for the reply!

Here is the result of `make VERBOSE=1` https://pastebin.com/QhpDEjXZ  (with "_py" set to 3.6 in cmake)
```
$ ldd vtkboolPython.so
        linux-vdso.so.1 (0x00007ffc6cbc9000)
        libvtkbool.so => /home/sean/src/vtkbool/build/libvtkbool.so (0x00007f529b6e8000)
        libvtkCommonExecutionModelPython36D-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonExecutionModelPython36D-7.1.so.7.1 (0x00007f529b42e000)
        libvtkWrappingPython36Core-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkWrappingPython36Core-7.1.so.7.1 (0x00007f529b1fd000)
        libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007f529ab52000)
        libvtkCommonCore-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonCore-7.1.so.7.1 (0x00007f529a620000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f529a297000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5299ea6000)
        libvtkIOLegacy-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkIOLegacy-7.1.so.7.1 (0x00007f5299bf2000)
        libvtkFiltersGeneral-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkFiltersGeneral-7.1.so.7.1 (0x00007f52996cf000)
        libvtkFiltersCore-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkFiltersCore-7.1.so.7.1 (0x00007f5299011000)
        libvtkCommonExecutionModel-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonExecutionModel-7.1.so.7.1 (0x00007f5298d54000)
        libvtkCommonDataModel-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonDataModel-7.1.so.7.1 (0x00007f52987a7000)
        libvtkCommonMath-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonMath-7.1.so.7.1 (0x00007f5298583000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f52981e5000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5297fcd000)
        libvtkCommonCorePython36D-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonCorePython36D-7.1.so.7.1 (0x00007f5297a64000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f5297832000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5297615000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f52973f6000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f52971f2000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f5296fef000)
        libvtksys-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtksys-7.1.so.7.1 (0x00007f5296da9000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f529bbda000)
        libvtkIOCore-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkIOCore-7.1.so.7.1 (0x00007f5296b34000)
        libvtkCommonComputationalGeometry-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonComputationalGeometry-7.1.so.7.1 (0x00007f52968e6000)
        libvtkCommonMisc-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonMisc-7.1.so.7.1 (0x00007f52966cc000)
        libvtkCommonTransforms-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonTransforms-7.1.so.7.1 (0x00007f529649c000)
        libvtkCommonSystem-7.1.so.7.1 => /usr/lib/x86_64-linux-gnu/libvtkCommonSystem-7.1.so.7.1 (0x00007f5296287000)
```

**Comment by zippy84** [comment]
It generally looks okay. How are you using the lib in Python? Did you add
the path to sys.path? Please try to run it with gdb.

sean-mcmahon <notifications@github.com> schrieb am Mi., 22. Jan. 2020,
23:21:

**Comment by sean-mcmahon** [comment]
Same as in the code example:
```
$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append('/home/sean/src/vtkbool/build')
>>> import os
>>> sys.path[-1]
'/home/sean/src/vtkbool/build'
>>> os.path.isdir(sys.path[-1])
True
>>> import vtk
>>> import vtkboolPython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/sean/src/vtkbool/build/vtkboolPython.so: undefined symbol: __gcov_merge_add
```

I'll try it with gdb

**Comment by zippy84** [comment]
There is the error. Your compiler uses -fprofile-arcs and -ftest-coverage.
Why do have this options? Is vtkbool_coverage on?

sean-mcmahon <notifications@github.com> schrieb am Do., 23. Jan. 2020,
01:15:

**Comment by sean-mcmahon** [comment]
Yep that's it. Thanks! The DVTKBOOL_COVERAGE flag snuck it's way in from the .travis.yml file. 

My work-around to get the python bindings generated was to change line 146 of CMakeLists.txt from:
`execute_process(COMMAND "${_vtk}/bin/vtkpython" -c "import sys; sys.stdout.write('.'.join(map(str, sys.version_info[:2])))" OUTPUT_VARIABLE _py)` 
to 
 `execute_process(COMMAND "${_vtk}/bin/python3" -c "import sys; sys.stdout.write('.'.join(map(str, sys.version_info[:2])))" OUTPUT_VARIABLE _py)`
Then build and compile.

**Comment by zippy84** [comment]
Fine.
