### ISSUE TITLE
Cannot run python example code

### ISSUE THREAD

**Issue by zhouy34** [zippy84/vtkbool#33]
Hi,
I have compiled vtkbool successfully. I can import it. When I try the python example in README.md, I got an error.
![Screenshot from 2020-03-10 11-36-21](https://user-images.githubusercontent.com/62020741/76329837-75a34300-62c3-11ea-883a-7b95894b0db4.png)
Message of error:
![Screenshot from 2020-03-10 11-38-02](https://user-images.githubusercontent.com/62020741/76329968-9e2b3d00-62c3-11ea-98d9-59841389096e.png)

**Comment by zippy84** [comment]
Sounds like this problem https://vtk.org/Wiki/VTK/FAQ#Why_do_I_get_the_Python_error_--_ValueError:_method_requires_a_VTK_object.3F

**Comment by zhouy34** [comment]
Yes, you are right. Thanks a lot.

**Comment by zippy84** [comment]
You are welcome :smiley:

**Comment by lp19950815** [comment]
可以请教一个你的vtkbool是如何编译过的吗

**Comment by lp19950815** [comment]
Where does vtkboolPython come from? Is the path of sys.path.append the path generated by vtkbool compilation?
