### ISSUE TITLE
Output mesh is fragmented

### ISSUE THREAD

**Issue by mamakovt** [zippy84/vtkbool#34]
Hello. There is a case with finding intersection between 2 toruses. 

![image](https://user-images.githubusercontent.com/18405193/80371950-6429f080-889b-11ea-9875-ecb361ac6a94.png)
Input: 2 toruses with a shifting. Quality of the mesh is pretty high (40Mb stl binary), holes between parts have approximately 1-2 triangles in the width. 
Also, execution time is close to 5min on modern PC. Union and difference finished in ~15 minutes with the same result.

**Comment by zippy84** [comment]
Hello. Please provide your meshes.

**Comment by mamakovt** [comment]
Second one was created with small shifting
https://drive.google.com/file/d/1-W92-IT6qb-cHuDynMcZbiCyOTN4rpav/view?usp=sharing
https://drive.google.com/file/d/1y1vqhKC3DBMdlMKy5lrzBjHqD_GMPV1q/view?usp=sharing

**Comment by zippy84** [comment]
Please try this branch https://github.com/zippy84/vtkbool/tree/test. It is 80% faster than the master version. It is still not fast enough. I figured out that GetPoint costs a lot of time. Actually I don't know how to solve this. But it is better than before.

The result seems to be correct. There are no gaps:

![torus](https://user-images.githubusercontent.com/373343/80819716-d2412100-8bd5-11ea-8044-61edc7e1bf88.png)
