### ISSUE TITLE
Boolean operation issue.

### ISSUE THREAD

**Issue by hwkim0325** [zippy84/vtkbool#36]
I'm trying to use boolean operation(union, intersection,  difference)
However, when I executed the operation my qt application got this error.

예외가 throw됨: 읽기 액세스 위반입니다.
_Pnext이(가) 0x1A400000008였습니다.
![image](https://user-images.githubusercontent.com/40055222/96081936-49a10d80-0ef5-11eb-98a5-aecedfb1ab86.png)
![image](https://user-images.githubusercontent.com/40055222/96081970-56256600-0ef5-11eb-948d-673ad36cf3e7.png)

What am I doing wrong?

vtkSmartPointer<vtkPolyData> MeshEditor::BooleanOperation(BooleanOperationMode mode,vtkSmartPointer<vtkPolyData> data1, vtkSmartPointer<vtkPolyData> data2) {

	vtkSmartPointer<vtkBooleanOperationPolyDataFilter> booleanOperation = vtkSmartPointer<vtkBooleanOperationPolyDataFilter>::New();
	vtkPolyDataBooleanFilter *booleanOperation2 = vtkPolyDataBooleanFilter::New();
	switch (mode) {
	case BooleanOperationMode::UNION:
		booleanOperation->SetOperationToUnion();
		booleanOperation2->SetOperModeToUnion();
		break;
	case BooleanOperationMode::INTERSECTION:
		booleanOperation->SetOperationToIntersection();
		booleanOperation2->SetOperModeToIntersection();
		break;
	case BooleanOperationMode::DIFFERENCE:
		booleanOperation->SetOperationToDifference();
		booleanOperation2->SetOperModeToDifference();
		break;
	}

	booleanOperation->SetInputData(0, data1);
	booleanOperation->SetInputData(1, data2);
	booleanOperation->Update();
	
	vtkSmartPointer<vtkTriangleFilter> triangleFilter = vtkSmartPointer<vtkTriangleFilter>::New();
	triangleFilter->SetInputData(data1);
	triangleFilter->Update();
	vtkSmartPointer<vtkTriangleFilter> triangleFilter2 = vtkSmartPointer<vtkTriangleFilter>::New();
	triangleFilter2->SetInputData(data2);
	triangleFilter2->Update();

	booleanOperation2->SetInputConnection(0, triangleFilter->GetOutputPort());
	booleanOperation2->SetInputConnection(1, triangleFilter2->GetOutputPort());
	booleanOperation2->SetOperModeToUnion();
	booleanOperation2->Update();

	vtkSmartPointer<vtkPolyDataNormals> normalGenerator = vtkSmartPointer<vtkPolyDataNormals>::New();
	normalGenerator->SetInputData(booleanOperation2->GetOutput());
	normalGenerator->ComputePointNormalsOn();
	normalGenerator->ComputeCellNormalsOn();
	normalGenerator->Update();

	return normalGenerator->GetOutput();
}

**Comment by zippy84** [comment]
I can't say anything about it, unless you provide your meshes.

**Comment by hwkim0325** [comment]
[Meshes.zip](https://github.com/zippy84/vtkbool/files/5388765/Meshes.zip)
Here is my meshes!

**Comment by zippy84** [comment]
I tried it with my version:

![hand](https://user-images.githubusercontent.com/373343/96275248-cacdd280-0fd1-11eb-8845-9ef0104e7cd4.png)

It works as expected.

What version do you use?

**Comment by hwkim0325** [comment]
I use VTK 8.2, Qt 5.9.2
Besides, I use the Visual-Studio 2015 version!

**Comment by zippy84** [comment]
Of vtkbool.

**Comment by hwkim0325** [comment]
![image](https://user-images.githubusercontent.com/40055222/97395910-5710bb80-1929-11eb-8960-bef3f9dc012d.png)
I got the latest version!
![image](https://user-images.githubusercontent.com/40055222/97396008-8c1d0e00-1929-11eb-859f-a8d041035090.png)
And I got this error recently ...

**Comment by zippy84** [comment]
So what is the problem? I cannot see my code in your screenshots.

**Comment by zippy84** [comment]
I'm closing this because there is of no response.

**Comment by hwkim0325** [comment]
I solved the problem, thanks.
