### ISSUE TITLE
can not compile in VS2015

### ISSUE THREAD

**Issue by liangbright** [zippy84/vtkbool#4]
Hello,  code can not compile in vs 2015
VS does not allow this: double pts_[numPts][3], double [num][3]  in vtkPolyDataBooleanFilter.cxx
Variable Length Array is not standard in C++

**Comment by zippy84** [comment]
Okay, I will fix this next time. But it is not very difficult to replace this with dynamical allocation.

**Comment by jpuhl** [comment]
Hi, I have created a pull request (https://github.com/zippy84/vtkbool/pull/8) since I already had converted it some time ago for my student job. I hope you can use it!

**Comment by zippy84** [comment]
Thanks for your support. I will try to merge some of your changes in my next release.

**Comment by zippy84** [comment]
The newest version, starting from 64296a7, is compilable with MSVC.
