### ISSUE TITLE
Target "vtkbool" links to target "VTK::WrappingPythonCore" but the target   was not found

### ISSUE THREAD

**Issue by 345950647** [zippy84/vtkbool#42]
How could I fix this problem. I used vcpkg and installed vtk.

**Comment by zippy84** [comment]
The python wrapper does not work for VTK9. Unfortunately...

**Comment by 345950647** [comment]
> The python wrapper does not work for VTK9. Unfortunately...

I have tried vtk8, vtk7 and vtk6. They all have same issue. WrappingPythonCore can not be found. I used windows as the platform. Should I try with linux?
