### ISSUE TITLE
Build error with vtk_wrap_hierarchy with VTK9

### ISSUE THREAD

**Issue by bluelightning32** [zippy84/vtkbool#44]
With VTK-9.0.1 that comes default in Fedora 34, I'm getting a compilation error building vtkbool.
```
CMake Error at vtkbool/CMakeLists.txt:113 (include):
  include could not find load file:

    vtkWrapHierarchy


CMake Error at vtkbool/CMakeLists.txt:114 (vtk_wrap_hierarchy):
  Unknown CMake command "vtk_wrap_hierarchy".
```

It's because vtkWrapHierarchy was removed in https://github.com/Kitware/VTK/commit/8d61ac62bfb3c532d1d3506d5f7fd495e49c4295.

I'm not using the PythonWrapper. Maybe you could disable it by default in VTK 9 until this problem is fixed?
```
-        if(VTK_WRAP_PYTHON)
+        if(VTK_WRAP_PYTHON AND ${VTK_MAJOR_VERSION} LESS 9)
```

**Comment by AlexLuya** [comment]
Same error here
