### ISSUE TITLE
Crash on combining certain models

### ISSUE THREAD

**Issue by mikebind** [zippy84/vtkbool#46]
Hello, I have been using vtkbool extensively through Slicer's "Combine Models" wrapper.  Mostly, it works very well and is very helpful.  However, I have run into a case where when I try to find the union of two overlapping models vtkbool crashes.  I have tried using Slicer surface toolbox's "Clean" and "Compute Normals" with auto-orientation to clean up any coincident points and fix any problematic normal vectors (I believe these use vtkCleanPolyData an vtkPolyDataNormals under the hood), but these pre-processing steps do not help.  The models which cause the crash are available at https://www.dropbox.com/sh/ael0c6hw8xs7nb8/AABuDKGnZUGQ0o47gjTzQlsRa?dl=0  
I'm not sure how to diagnose what might be going wrong, vtkbool usually "just works".  There are no error messages which are logged in Slicer, the application just crashes.

**Comment by zippy84** [comment]
Should work now.

**Comment by JuanMPinera** [comment]
Hello,
We encountered this same error in the past, and over time you managed to fix it in the 5.0.x versions. In those versions, when "Combine Models" encounters an error, it generates an empty model, and Slicer continues working. However, I recently tried updating to the Stable 5.6.2 version and am experiencing the same problem as before when an error occurs, Slicer closes.

I understand this was a bug that was previously fixed and has now reappeared. Can you fix this?

Thanks

**Comment by zippy84** [comment]
Can you send me your files that are causing this crash? How do you know
it's a problem of vtkbool?

JuanMPinera ***@***.***> schrieb am Fr., 30. Aug. 2024, 16:10:

**Comment by JuanMPinera** [comment]
Hello, I´m not sure if it´s a vtkbool problem, I read this topic: https://discourse.slicer.org/t/slicer-crash-when-combining-surface-models/20108 where Andras redirect the problem to here. And it´s the same problem.
Thanks in advance
