### ISSUE TITLE
please help install

### ISSUE THREAD

**Issue by derekeden** [zippy84/vtkbool#52]
can you please add instructions on how  to install for a general newbie?

Can I use my pip installed version of VTK? Do I have to build from source? Where is my VTK_DIR?

I'm getting this error msg when trying to install using cmake.. I have VTK installed via pip

![image](https://user-images.githubusercontent.com/36650862/177246532-e21d5cc9-24c7-4023-ad6e-c0b0853a2691.png)

**Comment by zippy84** [comment]
Unfortunately you have to build VTK from source. Currently there is no pip package.
