### ISSUE TITLE
Question on vtkbool - the way to find error code

### ISSUE THREAD

**Issue by LovDyn** [zippy84/vtkbool#54]
Hello, zippy84

I am enjoying to use yours.
I have a question fo using vtkbool.

during the run of my app, I saw the below message during the boolean for two objects.

I'd like to get this code with a flag variable. is it possible to get?
or I need to check with another function?

actually this is the issue for No contact between two polydata during the boolean.
if possible to get the flag in vtkbool, I'd like to use it. Could you review my question? 

ERROR: In vtkPolyDataBooleanFilter.cxx, line 163
vtkPolyDataBooleanFilter (00000258A7796B20): Inputs have no contact.

Thanks

**Comment by zippy84** [comment]
Yes, it's described here: https://kitware.github.io/vtk-examples/site/Cxx/Utilities/ObserveError/

**Comment by LovDyn** [comment]
> Yes, it's described here: https://kitware.github.io/vtk-examples/site/Cxx/Utilities/ObserveError/

Hello, zippy84

Thank you for the fast reply. I'll look into the article. Have a nice day.
