### ISSUE TITLE
Way to turn off the console script.

### ISSUE THREAD

**Issue by LovDyn** [zippy84/vtkbool#55]
Hello, zippy84

May I have a question for turning off the debug script during boolean operation?
during the boolean, I watched so much lines in my console window. 
I'd like to control it to check the performance of my app.

the below is a part of script shown. Please review.

GetEdgePolys()
polyId 88, ptIdA 115, ptIdB 112
polyId 89, ptIdA 377, ptIdB 378
GetEdgePolys()
polyId 4762, ptIdA 473, ptIdB 474
polyId 4763, ptIdA 2577, ptIdB 2582
GetLoc() -> polyId 88, cA 2, cB 2
GetLoc() -> polyId 89, cA 2, cB 2
GetLoc() -> polyId 4762, cA 2, cB 2
GetLoc() -> polyId 4763, cA 2, cB 2
polyId 88, sA 0, loc 1
polyId 89, sA 1, loc 2
polyId 4762, sB 0, loc 1
polyId 4763, sB 1, loc 2
line 53
GetEdgePolys()
polyId 88, ptIdA 114, ptIdB 115
polyId 89, ptIdA 378, ptIdB 379
GetEdgePolys()
polyId 4764, ptIdA 474, ptIdB 475
polyId 4765, ptIdA 2576, ptIdB 2577
GetLoc() -> polyId 88, cA 2, cB 2
GetLoc() -> polyId 89, cA 2, cB 2
GetLoc() -> polyId 4764, cA 2, cB 2
GetLoc() -> polyId 4765, cA 2, cB 2
polyId 88, sA 0, loc 1
polyId 89, sA 1, loc 2
polyId 4764, sB 0, loc 1
polyId 4765, sB 1, loc 2
line 54

**Comment by zippy84** [comment]
You have to disable VTKBOOL_DEBUG.
