### ISSUE TITLE
Crash On CombineRegions( ) method when execute SetOperModeToDifference

### ISSUE THREAD

**Issue by jealtw** [zippy84/vtkbool#64]
Hi Ronald. Firstly, thank you very much for your excellent work. 
Recently I've been using vtkbool to do difference operation of two vtkPolyData. When the program run to CombineRegions() method, it will crash. And I found that the crash happened at Line2894~Line2895 in vtkPolyDataBooleanFilter.cxx file. When the crash happens, the number of 'regsB->GetNumberOfCells()' is larger than the number of 'scalarsB->GetSize()', so when the iteration variable 'i' is larger than the number of 'scalarsB->GetSize()', access violation occurs. I tried to change the code to avoid the access violation problem, and the program can run and get the output vtkPolyData, but the result vtkPolyData seems to be the result of Union instead of Difference.  And if I use SetOperModeToUnion, the result seems to be result of Difference instead of Union, very strange behavior.
Can you give any help about this problem? 
I've created a repository for my test program and test data used in my code. You can find the repository by the following link : [vtkboolTest](https://github.com/jealtw/vtkboolTest). 

Thanks again for your great library!

**Comment by zippy84** [comment]
Hello.

Your meshes have different problems:

1. Data0-Union.stl has wrong oriented surface normals - therefore union and difference will not work as expected - pls check it with NormalGlyphs in ParaView 
2. Data3-Crash.stl has boundary edges that are involved in the intersection - pls check it with FeatureEdges in ParaView

I couldn't reproduce your issue with line 2894/2895.

**Comment by jealtw** [comment]
> 

Ronald, thanks for your quick reply!
The data is generated through the following steps:
1. Generate a polygon inside a plane
2. apply vtkLinearExtrusionFilter to the polygon, then Data3 is generated
3. apply vtkPolyDataNormals with AutoOrientNormalsOff(), then Data0 is generated
Should I just use AutoOrientNormalsOn to resolve the wrong oriented surface normals issue of Data0?

Besides, I wonder if you can give any suggestions about how to preprocess the above Data0 or Data3 in order to get the correct   
 result with vtkbool ?

**Comment by jealtw** [comment]
> Hello.
> 
> Your meshes have different problems:
> 
> 1. Data0-Union.stl has wrong oriented surface normals - therefore union and difference will not work as expected - pls check it with NormalGlyphs in ParaView
> 2. Data3-Crash.stl has boundary edges that are involved in the intersection - pls check it with FeatureEdges in ParaView
> 
> I couldn't reproduce your issue with line 2894/2895.

Ronald, thanks for your quick reply!
The data is generated through the following steps:
1. Generate a polygon inside a plane
2. apply vtkLinearExtrusionFilter to the polygon, then Data3 is generated
3. apply vtkPolyDataNormals with AutoOrientNormalsOff(), then Data0 is generated
Should I just use AutoOrientNormalsOn to resolve the wrong oriented surface normals issue of Data0?

Besides, I wonder if you can give any suggestions about how to preprocess the above Data0 or Data3 in order to get the correct   
 result with vtkbool ?

**Comment by jealtw** [comment]
> But I think you are right. It must be
> 
> ```
> scalarsA = vtkIdTypeArray::SafeDownCast(regsA->GetCellData()->GetScalars());
> scalarsB = vtkIdTypeArray::SafeDownCast(regsB->GetCellData()->GetScalars());
> ```
> 
> instead of GetPointData.

Right. With the above change, it will not crash any more.  Thanks again!

**Comment by jealtw** [comment]
Hi Ronald, I have another question for your help.  I have a STL file [Result_Extrusion.stl](https://github.com/jealtw/vtkboolTest/blob/cdd8f13253e005608cc852f22f4b3a03d6f9cd7d/Result_Extrusion.stl) , I want to use vtkbool to operate on this data and another data, but the normals of this data is incorrect even after I use vtkPolyDataNormals. So no result will be generate after use vtkbool.  How can I get the correct normals of this data, can you give any help? I have also post this on VTK Discuss[How to get the correct Normals of my STL file, Can anyone give any help?](https://discourse.vtk.org/t/how-to-get-the-correct-normals-of-my-stl-file-can-anyone-give-any-help/12173)

**Comment by zippy84** [comment]
Your file is not available.

**Comment by jealtw** [comment]
> Your file is not available.

Sorry for the inconvenience. You can goto "Code" downlist and then click "Download ZIP" to download the whole as a zip file, and then unzip it to get the "Result_Extrusion.stl" file.  If you still cann't get it, please tell me your email in private, my email is jealtw@hotmail.com.

Besides, about "Data3-Crash.stl has boundary edges that are involved in the intersection - pls check it with FeatureEdges in ParaView", how to remove the boundary edges so that they will not involved in the intersection?

**Comment by jealtw** [comment]
Hi Ronald, it seems that after bool operation by vtkbool, the output result vtkPolyData's normals is incorrect. For example, vtkPolyDataA  as input data 0 (with its normals point to outside of its surface)
vtkPolyDataB  as input data 1(with its normals point to outside of its surface)
Then use vtkBool::SetOperModeToDifference(), set vtkPolyDataC as the output result, and I found that part of the vtkPolyDataC has its normals point to outside of its surface, and the other part of the vtkPolyDataC has its normals point to inside of its surface, the part with normals point to outside of surface come from vtkPolyDataA, and the other part with normals point to inside of surface come from vtkPolyDataB.  Then even after I use vtkPolyDataNormals to vtkPolyDataC, still get the result of above mentioned instead of geting the correct result which should be with all normals point to outside or inside of surface.  So when I need to use vtkPolyDataC to do further boolean operation with vtkBool library, it will fail to get the result.  How to deal with this case, can you give any help?  In fact, I need to do multiple  boolean operation in pipeline.  You can use Data0-Union.stl  and Data1-Union.stl from [vtkBoolTest](https://github.com/jealtw/vtkboolTest) to reproduce the above phenomenon.

**Comment by zippy84** [comment]
Hi.

Try this script:

```python
#!/usr/bin/env python
# *-* coding: UTF-8 *-*

import sys
sys.path.extend(['/home/zippy/vtkbool/build/lib/python3.11/site-packages/vtkbool'])

from vtkmodules.vtkIOLegacy import vtkPolyDataReader, vtkPolyDataWriter
from vtkmodules.vtkIOGeometry import vtkSTLReader, vtkSTLWriter
from vtkmodules.vtkFiltersCore import vtkCleanPolyData, vtkPolyDataNormals, vtkTriangleFilter
from vtkBool import vtkPolyDataBooleanFilter

readerA = vtkSTLReader()
readerA.SetFileName('Data0-Union.stl')

readerB = vtkSTLReader()
readerB.SetFileName('Data1-Union.stl')

normals = vtkPolyDataNormals()
normals.SetInputConnection(readerA.GetOutputPort())
normals.FlipNormalsOn() # important

bf = vtkPolyDataBooleanFilter()
bf.SetInputConnection(0, normals.GetOutputPort())
bf.SetInputConnection(1, readerB.GetOutputPort())
bf.SetOperModeToDifference()

clean = vtkCleanPolyData()
clean.SetInputConnection(bf.GetOutputPort())

writer = vtkPolyDataWriter()
writer.SetFileName('lines.vtk')
writer.SetInputConnection(bf.GetOutputPort(2))
writer.Update()

writer2 = vtkPolyDataWriter()
writer2.SetFileName('diff_result.vtk')
writer2.SetInputConnection(clean.GetOutputPort())
writer2.Update()

tf = vtkTriangleFilter() # important for stl export
tf.SetInputConnection(clean.GetOutputPort())

writer3 = vtkSTLWriter()
writer3.SetFileName('diff_result.stl')
writer3.SetInputConnection(tf.GetOutputPort())
writer3.Update()
[results.zip](https://github.com/zippy84/vtkbool/files/12419510/results.zip)

```
The result is correct. See my attachments.

**Comment by jealtw** [comment]
> Hi.
> 
> Try this script:
> 
> ```python
> #!/usr/bin/env python
> # *-* coding: UTF-8 *-*
> 
> import sys
> sys.path.extend(['/home/zippy/vtkbool/build/lib/python3.11/site-packages/vtkbool'])
> 
> from vtkmodules.vtkIOLegacy import vtkPolyDataReader, vtkPolyDataWriter
> from vtkmodules.vtkIOGeometry import vtkSTLReader, vtkSTLWriter
> from vtkmodules.vtkFiltersCore import vtkCleanPolyData, vtkPolyDataNormals, vtkTriangleFilter
> from vtkBool import vtkPolyDataBooleanFilter
> 
> readerA = vtkSTLReader()
> readerA.SetFileName('Data0-Union.stl')
> 
> readerB = vtkSTLReader()
> readerB.SetFileName('Data1-Union.stl')
> 
> normals = vtkPolyDataNormals()
> normals.SetInputConnection(readerA.GetOutputPort())
> normals.FlipNormalsOn() # important
> 
> _writer = vtkPolyDataWriter()
> _writer.SetFileName('flipped.vtk') # check this with NormalGlyphs (see also my screenshot)
> _writer.SetInputConnection(normals.GetOutputPort())
> _writer.Update()
> 
> bf = vtkPolyDataBooleanFilter()
> bf.SetInputConnection(0, normals.GetOutputPort())
> bf.SetInputConnection(1, readerB.GetOutputPort())
> bf.SetOperModeToDifference()
> 
> clean = vtkCleanPolyData()
> clean.SetInputConnection(bf.GetOutputPort())
> 
> writer = vtkPolyDataWriter()
> writer.SetFileName('lines.vtk')
> writer.SetInputConnection(bf.GetOutputPort(2))
> writer.Update()
> 
> writer2 = vtkPolyDataWriter()
> writer2.SetFileName('diff_result.vtk')
> writer2.SetInputConnection(clean.GetOutputPort())
> writer2.Update()
> 
> tf = vtkTriangleFilter() # important for stl export
> tf.SetInputConnection(clean.GetOutputPort())
> 
> writer3 = vtkSTLWriter()
> writer3.SetFileName('diff_result.stl')
> writer3.SetInputConnection(tf.GetOutputPort())
> writer3.Update()
> 
> features = vtkFeatureEdges()
> features.SetInputConnection(clean.GetOutputPort())
> features.BoundaryEdgesOn()
> features.FeatureEdgesOff()
> features.NonManifoldEdgesOff()
> features.Update()
> 
> assert features.GetOutput().GetNumberOfLines() == 0
> ```
> 
> The result is correct. See my attachments.
> 
> [results.zip](https://github.com/zippy84/vtkbool/files/12419510/results.zip)
> 
> ![grafik](https://user-images.githubusercontent.com/373343/262708040-2df54b02-71c9-480b-8a70-d9eb47a5378b.png)

Hi，Ronald， Thanks for your reply. I know that Data0's Normals should be flipped so that Data0 difference Data1 can generate  result with vtkbool.  
I have checked the results.zip attachment.  And I found that "diff_result.stl" has the phenomenon that I mentioned before, that is "part of the diff_result.stl has its normals point to outside of its surface, and the other part of the diff_result.stl has its normals point to inside of its surface", you can see it with NormalGlyphs in ParaView. 
[IncorrectNormals1](https://github.com/jealtw/vtkboolTest/blob/main/IncorrectNormals.png)    
[IncorrectNormals2](https://github.com/jealtw/vtkboolTest/blob/main/IncorrectNormals2.png)
Is this right phenomenon?

**Comment by jealtw** [comment]
Ronald, I cann't reproduce the phenomenon even with old version and do not know why. 
Anyway, I will try the latest version on master, if any issues, I will contact you for help.  Thanks for your excellent work!

**Comment by zippy84** [comment]
It's fixed.
