### ISSUE TITLE
How to resolve "Strips are invalid Issue" issues ?

### ISSUE THREAD

**Issue by jealtw** [zippy84/vtkbool#65]
Hi Ronald, I have 2 new datas to do boolean intersection. 
Data0 is [InvalidStrip-Data0.stl](https://github.com/jealtw/vtkboolTest/blob/main/InvalidStrip-Data0.stl)
Data1 is [InvalidStrip-Data1.stl](https://github.com/jealtw/vtkboolTest/blob/main/InvalidStrip-Data1.stl)
When I do "SetOperModeToIntersection()", it gives error with information "Strips are invalid". 
How can I get the expected intersection result with some kind of necessary preprocessing steps, can you give any help?

**Comment by zippy84** [comment]
Hi.

Pls read https://github.com/zippy84/vtkbool#errors-and-their-meaning.

It's the first point under "Strips are invalid.".

[InvalidStrip-Data1.stl](https://github.com/jealtw/vtkboolTest/blob/main/InvalidStrip-Data1.stl) is an assembly. Therefore it could not work.

**Comment by jealtw** [comment]
[InvalidStrip-Data1.stl](https://github.com/jealtw/vtkboolTest/blob/main/InvalidStrip-Data1.stl) is generated by append a second vtkPolyData to a first vtkPolyData.

**Comment by jealtw** [comment]
And I don't understand the second point under "Strips are invalid" --- "there are different intersection points with the same capturing point (whether they are connected by other lines or not) - this is a limitation of the filter".
1. What is a capturing point ?
2. Can you  give a screen capture of the phenomenon described by second point under "Strips are invalid"?

**Comment by zippy84** [comment]
> [InvalidStrip-Data1.stl](https://github.com/jealtw/vtkboolTest/blob/main/InvalidStrip-Data1.stl) is generated by append a second vtkPolyData to a first vtkPolyData.

And this creates the assembly.

> And I don't understand the second point under "Strips are invalid" --- "there are different intersection points with the same capturing point (whether they are connected by other lines or not) - this is a limitation of the filter".
> 
>     1. What is a capturing point ?
> 
>     2. Can you  give a screen capture of the phenomenon described by second point under "Strips are invalid"?

This is hard to explain. The error occurs because of the assembly.

**Comment by jealtw** [comment]
> > [InvalidStrip-Data1.stl](https://github.com/jealtw/vtkboolTest/blob/main/InvalidStrip-Data1.stl) is generated by append a second vtkPolyData to a first vtkPolyData.
> 
> And this creates the assembly.
> 
> > And I don't understand the second point under "Strips are invalid" --- "there are different intersection points with the same capturing point (whether they are connected by other lines or not) - this is a limitation of the filter".
> > ```
> > 1. What is a capturing point ?
> > 
> > 2. Can you  give a screen capture of the phenomenon described by second point under "Strips are invalid"?
> > ```
> 
> This is hard to explain. The error occurs because of the assembly.

How to try to avoid "Strips are invalid" issue , especially to avoid the second point under "Strips are invalid", can you give any suggestions? If the data just meets the second point, is there any methods to avoid it?

**Comment by zippy84** [comment]
As I said, it is hard to explain here. Pls look at https://github.com/zippy84/vtkbool/blob/1295817b4ab015f82e1af5fb54e6ddeeda2f4504/testing/test_filter.py#L949. The test will fail because there is one capturing point that is shared by two different points in contLines. Normally a capturing point is used by only one point in contLines. That's the short description.

**Comment by jealtw** [comment]
Ronald, thanks for your help and great work!

**Comment by jealtw** [comment]
Hi Ronald, today I found another issue, please see [vtkbool-Runtime-Error](https://github.com/jealtw/vtkboolTest/blob/main/vtkbool-Runtime-Error.png).  I use debug mode vtkbool under debug mode. I try to investigate the reason of the bug, but still have no solution. Can you give any help? Thanks.

**Comment by jealtw** [comment]
Hi Ronald,  today during debug my program, the  [vtkbool-Runtime-Error](https://github.com/jealtw/vtkboolTest/blob/main/vtkbool-Runtime-Error.png)  issue recur. And Now I can find the exact issue position. Please see [Variable-Id-without initialized](https://github.com/jealtw/vtkboolTest/blob/main/Variable-Id-without%20initialized.png) for the detail information.

**Comment by zippy84** [comment]
Fixed, but why are you using the debug-mode of vtkbool? It's only for the development of the library and should not to be confused with the build type.

**Comment by jealtw** [comment]
Because with debug-mode of vtkbool, I can track the console output message of vtkbool, so that I can know immediately whether or not vtkbool will successfully produce output. And if not, I can find the rough fail position of vtkbool.
