### ISSUE TITLE
Contact ends suddenly issue

### ISSUE THREAD

**Issue by jealtw** [zippy84/vtkbool#67]
Hi Ronald, when I use [FrontSurface.stl](https://github.com/jealtw/vtkboolTest/blob/main/FrontSurface.stl) and [Name.stl](https://github.com/jealtw/vtkboolTest/blob/main/Name.stl) to do boolean Union operation, it failed with error message "contact ends suddenly". During debug, I found there are several points which GetNumberOfIds==1. And then I tried to zoom in FrontSurface.stl and contLines.vtk enough in ParaView, and found that in FrontSurface.stl, there are some line gaps in the front plane which may be the reason why contact ends suddenly. But in fact, [FrontSurface.stl](https://github.com/jealtw/vtkboolTest/blob/main/FrontSurface.stl)  is generated by another boolean operation, it is  generated by [ExtrusionContour.stl](https://github.com/jealtw/vtkboolTest/blob/main/ExtrusionContour.stl) and [ExtrusionDiffImg.stl](https://github.com/jealtw/vtkboolTest/blob/main/ExtrusionDiffImg.stl) with boolean intersection. So  I think FrontSurface.stl should have smooth enough front plane, but now in fact it is not. What kind of operation should I do to get smooth enough result to overcome the "contact ends suddenly" issue. Can you give any suggestion?

Another question : during use vtkPolyDataBooleanFilter, it will fail to generate boolean result from time to time due to "Strips are invalid" issue. But I find that if firstly save the input datas into stl files, then read the stl file again into memory and then do boolean operation, the same datas will succeed to generate boolean result without "Strips are invalid" issue, a very strange behavior. Do you know the reason of this phenomenon?

Thanks.

**Comment by jealtw** [comment]
Please take a look at [FrontFace-Contact ends suddenly.png](https://github.com/jealtw/vtkboolTest/blob/main/FrontFace-Contact%20ends%20suddenly.png) and [FrontFace-Contact ends suddenly-2.png](https://github.com/jealtw/vtkboolTest/blob/main/FrontFace-Contact%20ends%20suddenly.png), which records the line gaps in the front plane of FrontSurface.stl.

**Comment by zippy84** [comment]
I want to help you, but something is wrong. Please check your files. FrontSurface cannot be constructed with ExtrusionContour and ExtrusionDiffImg.

**Comment by jealtw** [comment]
> I want to help you, but something is wrong. Please check your files. FrontSurface cannot be constructed with ExtrusionContour and ExtrusionDiffImg.

Sorry.  I mean FrontSurface is generated by ExtrusionContour and ExtrusionDiffImg with boolean intersection. And sometimes the generated FrontSurface will have the issues I described above. The original ExtrusionContour and ExtrusionDiffImg files have been overwriten, so I can't find it now. If the phenomenon recurs, I will upload the files again.  Thanks.

I use vtkPolyDataBooleanFilter to do a series of boolean operations, and finally get the expected result. If any step the boolean operation fails, the afterwards steps will fail. And I found that any step has the possibility to fail due to two main issues. The first one is "Contact ends suddenly", the second one is "Strips are invalid", when one of the two issues occurs, I will fail to get the result.  I wonder if you have any suggestion to preprocess the input datas of vtkPolyDataBooleanFilter to try to avoid the above two issues.   For example, I used to try to do the following preprocess steps before call vtkPolyDataBooleanFilter on the output of vtkLinearExtrusionFilter which is one input of  vtkPolyDataBooleanFilter :
(1)vtkPolyDataNormals
(2)vtkSmoothPolyDataFilter
(3)vtkCleanPolyData
(4)vtkTriangleFilter
(5)vtkPolyDataNormals
But one of the above two issues still occurs from time to time.   

By the way, I don't know the underlying logic of vtkPolyDataBooleanFilter. Do you have any principle materails which can help to understand the algorithms in vtkPolyDataBooleanFilter?

**Comment by zippy84** [comment]
The issue cannot be reproduced.
