### ISSUE TITLE
Problem with boolean operations on a model

### ISSUE THREAD

**Issue by jpuhl** [zippy84/vtkbool#7]
Hello,
when I try to e.g. create the difference from "Skull.vtp" and "Cut Object.vtp", I don't get the expected result. Can you have a look at it? As you can see in the attached file "Result.vtp", there is no cut being done. Instead the objects are fused together. The other operations don't seem to work either.

The files used are in here:
[VTK Objects.zip](https://github.com/zippy84/vtkbool/files/1302720/VTK.Objects.zip)

Update:
I tested with debug build and I get an assert:
"vtkPolyDataBooleanFilter.cxx:1797: void vtkPolyDataBooleanFilter::MergePoints(vtkPolyData*, PolyStripsType&): Assertion `numPts > 0' failed."

Update2:
Upon further testing I discovered that the size is a problem. If I scale the models down it seems to work, but I have to use the difference2 operator instead of difference to get the result I need.

**Comment by zippy84** [comment]
Yes you are right, a wrong scaling could be a reason, a boolean operation will fail. The involved filters uses tolerences, based on fixed values. These tolerances may not work with big or too small modells. Some day I will find a good way to handle this.

**Comment by zippy84** [comment]
Please download or clone the newest version of my lib. Does the problem still exists? I tried it without any scaling and there was no error.

**Comment by jpuhl** [comment]
First of all thanks for updating the library :) Now it works with VS2015. The testcase I posted above works now, but if I try different objects it fails with an assert. I appended another testcase with a more detailed skull object and a different cut. 
[VTK Objects.zip](https://github.com/zippy84/vtkbool/files/1556539/VTK.Objects.zip)

Also I noticed that in line 364 and 412 of RmTrivials.cxx you should first check for the end() and then for the other condition of the for loop. So for you it might crash before that in your version if you don't fix it.

Also it would be really helpful if you could add way more comments (even German as they are now is fine for us) and choose names for the variables which makes it easier to understand what is happening. For now I imagine only you can debug it since you know your code.

**Comment by zippy84** [comment]
Thanks for your response and thanks for your feedback. I think it is still a problem with tolerances. I will fix this soon.

**Comment by zippy84** [comment]
Your example works, if you change the tolerance at https://github.com/zippy84/vtkbool/blob/f56aef2f244687d4403039dd5105e2a3ae2f7e4f/libs/vp/RmTrivials.cxx#L46 and https://github.com/zippy84/vtkbool/blob/f56aef2f244687d4403039dd5105e2a3ae2f7e4f/libs/vp/Tools.cxx#L245 to 1e-2.

**Comment by jpuhl** [comment]
Yes, that works better. I have attached three more cut objects where different errors occur. Hopefully they help you figuring out the remaining bugs.
[VTK Objects.zip](https://github.com/zippy84/vtkbool/files/1556932/VTK.Objects.zip)

**Comment by zippy84** [comment]
It works now! See the lastest commit 41999d92b6ad56e3d58ad74fedbe25ee8fac419d.
